#!/bin/bash

# Upload Vite-built PWA files to Google Cloud Storage
# Usage: ./upload-to-gcs.sh YOUR_BUCKET_NAME

set -e

if [ -z "$1" ]; then
    echo "Usage: $0 BUCKET_NAME"
    echo "Example: $0 my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# Build the production bundle
echo "Building production bundle..."
npm run build

echo "Uploading PWA files to gs://$BUCKET_NAME/..."

# Upload index.html (no cache)
echo "  Uploading index.html..."
gsutil -h "Content-Type:text/html" \
       -h "Cache-Control:no-cache, max-age=0" \
       cp dist/index.html "gs://$BUCKET_NAME/"

# Upload JS/CSS assets (long cache - they have content hashes)
echo "  Uploading assets..."
gsutil -h "Cache-Control:public, max-age=31536000" \
       -m cp -r dist/assets "gs://$BUCKET_NAME/"

# Upload manifest (generated by vite-plugin-pwa)
if [ -f "dist/manifest.webmanifest" ]; then
    echo "  Uploading manifest.webmanifest..."
    gsutil -h "Content-Type:application/manifest+json" \
           -h "Cache-Control:no-cache, max-age=0" \
           cp dist/manifest.webmanifest "gs://$BUCKET_NAME/"
fi

# Upload service worker (generated by vite-plugin-pwa)
if [ -f "dist/sw.js" ]; then
    echo "  Uploading sw.js..."
    gsutil -h "Content-Type:application/javascript" \
           -h "Cache-Control:no-cache, max-age=0" \
           cp dist/sw.js "gs://$BUCKET_NAME/"
fi

# Upload workbox files if they exist
if [ -d "dist/workbox-"* ] 2>/dev/null; then
    echo "  Uploading workbox files..."
    gsutil -h "Cache-Control:public, max-age=31536000" \
           -m cp -r dist/workbox-* "gs://$BUCKET_NAME/"
fi

# Upload icons
if [ -d "dist/icons" ]; then
    echo "  Uploading icons..."
    gsutil -h "Content-Type:image/png" \
           -h "Cache-Control:public, max-age=31536000" \
           -m cp -r dist/icons "gs://$BUCKET_NAME/"
fi

echo ""
echo "Successfully uploaded PWA to gs://$BUCKET_NAME/"
echo "URL: https://storage.googleapis.com/$BUCKET_NAME/index.html"
